### ISSUE TITLE
Create a banner linking to new license chooser from old chooser.

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cc.engine#24]
New chooser URL: https://chooser-beta.creativecommons.org/

**Comment by kgodey** [comment]
tagging @annatuma for language for the banner.

**Comment by annatuma** [comment]
Language:

"We are currently testing a new version of the License Chooser. Please consider using the <License Chooser Beta>[https://chooser-beta.creativecommons.org/], and leave us feedback on how we can improve."

**Comment by miracle-E** [comment]
@kgodey I'm an outreachy applicant, please how can I contribute?

**Comment by hugosolar** [comment]
Hey @miracle-E sorry but this issue is `CC staff only`.

**Comment by hugosolar** [comment]
Adding the `blocked` label because we're waiting Chooser beta is ready (last changes and legal revision)

**Comment by annatuma** [comment]
This is no longer blocked, @hugosolar - sorry that I missed updating this ticket more promptly.

The final language changes are in: https://github.com/creativecommons/chooser/issues/151
