### ISSUE TITLE
edit to the About the Licenses page

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/cc.engine#5]
To resolve some confusion within the CC Certificate course, we need to make a small edit to this page. It has been signed off by @peterspdx. 

The change is to the 1-sentence description of the Attribution-NoDerivs license, about 2/3 of the way down the page. 

Currently it says: "This license allows for redistribution, commercial and non-commercial, as long as it is passed along unchanged and in whole, with credit to you."

Please change it to read: This license lets others reuse the work for any purpose, including commercially; however, it cannot be shared with others in adapted form, and credit must be provided to you.

Thank you!

**Comment by aldenstpage** [comment]
Hi Sarah, I've shipped your change to the site. Please close this issue if it looks good. https://creativecommons.org/licenses/
